### ISSUE TITLE
Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by guilhermebc** [eKoopmans/html2pdf#116]
Hi, I'm having this problem while compiling my project using the html2pdf plugin.

If anyone can solve it, share it with me, I'll be grateful!

I tried installing 'fs' via npm install fs, but I did not succeed.

**ERROR in ./node_modules/jspdf/dist/jspdf.min.js
Module not found: Error: Can't resolve 'fs' in '/<project-root>/node_modules/jspdf/dist'
 @ ./node_modules/jspdf/dist/jspdf.min.js 50:10558-10571
 @ ./node_modules/html2pdf.js/dist/html2pdf.js**

**Comment by eKoopmans** [comment]
Hi @guilhermebc, thanks for flagging this issue! I found this related issue on jsPDF: MrRio/jsPDF#1764.

It is a bug in Webpack, see this comment/thread for more info:
https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285598881

Looks like the currently accepted solution is to add the following to your webpack config:

```js
node: {
   fs: "empty"
}
```

Note that this isn't an issue with my prebuilt version, because I use rollup rather than webpack.

**Comment by petekc1** [comment]
I'm still receiving an error after using this solution.

```
    const worker = html2pdf().from(element).save();
    console.log(worker);
```

```
Promise {_bitField: 0, _fulfillmentHandler0: undefined, _rejectionHandler0: undefined, _promise0: undefined, _receiver0: undefined, …}
_bitField
:
0
_fulfillmentHandler0
:
undefined
_promise0
:
undefined
_receiver0
:
undefined
_rejectionHandler0
:
undefined
_trace
:
CapturedTrace
_length
:
1
_parent
:
undefined
_promisesCreated
:
0
stack
:
"Error↵    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:56563:19)↵    at Promise._then (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:58351:17)↵    at Promise.then (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:58244:17)↵    at Promise.then_main (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:71737:38)↵    at Promise.thenCore (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:71762:28)↵    at Promise.then (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:71731:15)↵    at Promise.save (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:71604:79)↵    at InvoiceService.download (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:173877:83)↵    at Invoice.routes/invoices/invoice.Invoice.download (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:181574:29)↵    at CallScope.evaluate (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:37499:19)↵    at Call.callSource (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:40994:40)↵    at Object.download (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:41018:22)↵    at InvoiceSheetComponent.<anonymous> (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:171592:29)↵    at callCallback (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:122449:12)↵    at commitUpdateQueue (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:122482:7)↵    at commitLifeCycles (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:125949:11)↵    at commitAllLifeCycles (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:127027:7)↵    at HTMLUnknownElement.callCallback (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:111785:14)↵    at Object.invokeGuardedCallbackDev (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:111823:16)↵    at invokeGuardedCallback (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:111872:29)↵    at commitRoot (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:127166:7)↵    at completeRoot (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:128181:34)↵    at performWorkOnRoot (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:128125:9)↵    at performWork (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:128043:7)↵    at performSyncWork (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:128015:3)↵    at interactiveUpdates$1 (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:128282:7)↵    at interactiveUpdates (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:113835:10)↵    at dispatchInteractiveEvent (http://localhost:8080/app.fe35930936c81e6118f9.bundle.js:116213:3)"
__proto__
:
Error
attachExtraTrace
:
ƒ (error)
arguments
:
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]
caller
:
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]
length
```

**Comment by ImFranQ** [comment]
this works for me
```
node: {
   fs: "empty"
}
```
then I got this error:
```
Module not found: Error: Can't resolve 'child_process' in '/app/node_modules/html-pdf/lib'
```

**Comment by 87prashant** [comment]
> this works for me
> 
> ```
> node: {
>    fs: "empty"
> }
> ```
> 
> then I got this error:
> 
> ```
> Module not found: Error: Can't resolve 'child_process' in '/app/node_modules/html-pdf/lib'
> ```

I got same error too @eKoopmans
